[package]
name = "uplink_skeleton"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { git="https://github.com/DioxusLabs/dioxus", rev="651ab3e7e393f22f7aee0428bdc63cffcb1e0239" }
dioxus-hooks = { git="https://github.com/DioxusLabs/dioxus", rev="651ab3e7e393f22f7aee0428bdc63cffcb1e0239" }
dioxus-router = { git="https://github.com/DioxusLabs/dioxus", rev="651ab3e7e393f22f7aee0428bdc63cffcb1e0239" }
dioxus-desktop = { git="https://github.com/DioxusLabs/dioxus", rev="651ab3e7e393f22f7aee0428bdc63cffcb1e0239" }
fermi = { git="https://github.com/DioxusLabs/dioxus", rev="651ab3e7e393f22f7aee0428bdc63cffcb1e0239" }

ui-kit = { path = "../ui_kit" }
uuid = { version = "1.0", features = ["serde", "v4"] }
lipsum = "0.8.2"
warp = { git="https://github.com/Satellite-im/Warp.git", ref="master" }
names = "0.14.0"
titlecase = "2.2.1"
serde = "1.0.150"
serde_json = "1.0.89"
rand = "0.8.4"
image = "0.24.5"
chrono = "0.4.19"
substring = "1.4.5"
either = "1.6.1"
base64 = "0.20.0"
fluent-templates = "0.8.0"
unic-langid = "0.9.1"
timeago = "0.4.0"
dirs = "4.0.0"
opener = "0.5.0"
soloud = "1.0.2"
open = "3.2.0"

[build-dependencies]
glob = "0.3.0"
rsass = "0.26.0"

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.24.1"
objc = "0.2.7"