
name: Build Linux

on:
  push:
    branches:
      - "!*"
    tags:
      - "*"

jobs:
  check:
    name: Build Release Linux
    runs-on: ubuntu-latest
    steps:
      - name: Install libwebkit2gtk
        run: sudo apt-get install -y build-essential pkg-config libssl-dev libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev librust-alsa-sys-dev dpkg-dev gzip
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Build executable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.68.2
          override: true
      - run: cargo build --release -F production_mode
      - run: bash build_linux_installer.sh uplink ${{ github.ref_name }} amd64

      - name: Github Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/release/*.so
            target/release/uplink
            target/release/*.deb
            target/release/SHA256SUM