# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

on: [pull_request]

name: Cargo Workflow

jobs:
  check:
    name: Cargo Checks
    runs-on: ubuntu-latest
    steps:
      - name: Install libwebkit2gtk
        run: sudo apt-get install -y build-essential pkg-config libssl-dev libgtk-3-dev libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev librust-alsa-sys-dev
      - name: Install Protoc
        uses: arduino/setup-protoc@v1
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Run cargo checks
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.68.2
          override: true
          components: rustfmt, clippy
      - run: cargo clippy --no-deps -- -D warnings
      - run: cargo fmt --check
