name: Update PR's with latest dev
on:
   push:
     branches:
        - dev
jobs:
  shipit:
    name: shipit
    runs-on: ubuntu-latest
    steps:
      - uses: kevinrobayna/shipit@v2.0.0
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
