name: Update PRs on Dev Branch Changes

on:
  push:
    branches:
      - dev
  pull_request:
    types:
      - synchronize

jobs:
  update_prs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Update PRs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin dev

          # Check if there are any changes in the dev branch
          CHANGED_FILES=$(git diff --name-only origin/dev)

          # If there are changes, update the pull requests
          if [[ -n "$CHANGED_FILES" ]]; then
            PR_LIST=$(gh pr list --state open --base dev --json number -q '.[].number')

            # Update each open pull request with a custom commit message
            for PR_NUMBER in $PR_LIST; do
              gh pr merge $PR_NUMBER --merge --title "Update from dev branch" --body "This pull request has been updated with the latest changes from the dev branch."
            done
          else
            echo "No changes found in the dev branch. Skipping PR update."
          fi
